# Generated by Django 5.1.3 on 2024-12-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pnldata',
            options={'verbose_name': 'PnL Data', 'verbose_name_plural': 'PnL Data'},
        ),
        migrations.AlterModelOptions(
            name='userapikey',
            options={'verbose_name': 'User API Key', 'verbose_name_plural': 'User API Keys'},
        ),
    ]
